# permissions for end users to view pagerdutyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pagerdutyservice-viewer-role
rules:
- apiGroups:
  - core.strateos.com
  resources:
  - pagerdutyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.strateos.com
  resources:
  - pagerdutyservices/status
  verbs:
  - get
